<template>
  <f7-page name="home">
  <!-- Top Navbar -->
    <f7-navbar :sliding="false" large>
      <div>
        <f7-button class = "button-fill button" v-on:click="goBack()" style="text-align:left; width:100%"> Go Back </f7-button>
      </div>
      <h4 style="text-align:right; width: 100%;color: #005eb8;"> <div class="shadow_corner"><img class="logo" src="static/icons/logo.png" /></div></h4>
      <f7-nav-title-large sliding style="text-align:center; width: 100%; color: #005eb8"> Admin Registration </f7-nav-title-large>
    </f7-navbar>

  <!-- Page content-->

  <f7-block strong>
    <form @submit.prevent="onSignupClicked" action="" method="GET">
      <f7-list class = "login-list" no-hairlines-md>
        <f7-list-input class="email-input" :value="name" @input="name = $event.target.value" label="Enter your name" placeholder="John Smith" />
        <f7-list-input class="email-input" :value="email" @input="email = $event.target.value" label="Type in your work email address" type="email" placeholder="E-mail" />
        <f7-list-input :value="password" @input="password = $event.target.value" label="Choose a password" type ="password" placeholder="Password" />
        <f7-list-item class = "smart-select"   title="Choose Centre"> 
          <select v-model="centre">
            <option value="1">"Brentwood Centre"</option>
          <option value="2">"Shefford Health Centre"</option>
          <option value="3">"Cathedral Medical Centre"</option>
          <option value="4">"Staploe Medical Centre"</option>
          <option value="5">"Barclay Hall, Hoddesdon Parish Church"</option>
          <option value="6">"Moors Walk Surgery"</option>
          <option value="7">"Parkway Surgery"</option>
          <option value="8">"Sheepcot Medical Centre"</option>
          <option value="9">"The Colne Practice"</option>
          <option value="10">"Two Rivers Medical Centre"</option>
          <option value="11">"Kingsway Health Centre"</option>
          <option value="12">"Danbury Medical Centre"</option>
          <option value="13">"Whaddon Medical Centre"</option>
          <option value="14">"Fakenham Medical Practice"</option>
          <option value="15">"Kirkley Mill"</option>
          <option value="16">"Lionwood Medical Practice"</option>
          <option value="17">"St James Medical Practice"</option>
          <option value="18">"Swanton Morley Surgery"</option>
          <option value="19">"St Helena Tendring Centre"</option>
          <option value="20">"Stifford Clays Health Centre"</option>
          <option value="21">"Stansted Surgery"</option>
          <option value="22">"Swan Surgery"</option>
          <option value="23">"Barking Hospital+C4"</option>
          <option value="24">"Liberty Bridge (Sir Ludwig Guttman)"</option>
          <option value="25">"Bingfield"</option>
          <option value="26">"Lordship Lane Health Centre"</option>
          <option value="27">"Hurley Clinic"</option>
          <option value="28">"Bursted Wood Surgery"</option>
          <option value="29">"The Wilson Hospital"</option>
          <option value="30">"Fairhill Medical Practice"</option>
          <option value="31">"Ombersley Medical Centre"</option>
          <option value="32">"Riverside Surgery"</option>
          <option value="33">"Stourport Medical Centre"</option>
          <option value="34">"Louth Hospital"</option>
          <option value="35">"The Table Tennis Club Grantham Meres"</option>
          <option value="36">"Sparkhill Primary Care Centre"</option>
          <option value="37">"West Heath Surgery"</option>
          <option value="38">"Feldon Lane Medical Practice"</option>
          <option value="39">"Northway Medical Practice"</option>
          <option value="40">"Chelmsley Wood"</option>
          <option value="41">"Ryecroft Surgery"</option>
          <option value="42">"Nene Valley Surgery"</option>
          <option value="43">"Queensway Medical Centre"</option>
          <option value="44">"Weedon Surgery"</option>
          <option value="45">"Enki Medical"</option>
          <option value="46">"Bridgnorth Medical Practice"</option>
          <option value="47">"Smallthorne Branch Surgery"</option>
          <option value="48">"Wood Road Surgery"</option>
          <option value="49">"Priory Campus"</option>
          <option value="50">"Canalside Healthcare Centre"</option>
          <option value="51">"Long Lee"</option>
          <option value="52">"Skipton Hospital"</option>
          <option value="53">"Spring Hall Surgery"</option>
          <option value="54">"Tanfield View Medical Centre"</option>
          <option value="55">"The Rutland Centre"</option>
          <option value="56">"Brough Surgery"</option>
          <option value="57">"Church View Surgery"</option>
          <option value="58">"KC Stadium"</option>
          <option value="59">"Craven Road Medical Practice"</option>
          <option value="60">"East Park Medical Centre"</option>
          <option value="61">"Hillfoot"</option>
          <option value="62">"Birtley Medical Group"</option>
          <option value="63">"Flatt Walks Health Centre"</option>
          <option value="64">"North Carlisle Medical Practice"</option>
          <option value="65">"Derwent Practice"</option>
          <option value="66">"Filey Surgery"</option>
          <option value="67">"Lintonville"</option>
          <option value="68">"Anston Medical Centre"</option>
          <option value="69">"The Health Care Surgery"</option>
          <option value="70">"Woodhouse Health Centre"</option>
          <option value="71">"Grindon Lane Primary Care Centre"</option>
          <option value="72">"One Life"</option>
          <option value="73">"Queens Park Medical Centre"</option>
          <option value="74">"Haxby Health Centre"</option>
          <option value="75">"Church View Health Centre"</option>
          <option value="76">"Whitegate Health Centre"</option>
          <option value="77">"Tonge Moor Health Centre"</option>
          <option value="78">"Prestwich Walk in Centre"</option>
          <option value="79">"Puzey Family Practice"</option>
          <option value="80">"Chorley Surgery"</option>
          <option value="81">"Lytham PCC"</option>
          <option value="82">"ISSA Medical Centre"</option>
          <option value="83">"Alfred Barrow Health Centre"</option>
          <option value="84">"Dene Drive Primary Care Centre"</option>
          <option value="85">"St Peter's Centre"</option>
          <option value="86">"Birkenhead Medical Building"</option>
          <option value="87">"Barley Clough Medical Centre"</option>
          <option value="88">"Tilehurst Village Surgery"</option>
          <option value="89">"Chalfont Hospital"</option>
          <option value="90">"The Meads Medical Centre"</option>
          <option value="91">"Fareham Community Hospital"</option>
          <option value="92">"Abbey Court Medical Centre"</option>
          <option value="93">"Mocketts Wood"</option>
          <option value="94">"Queen Victoria memorial Hospital"</option>
          <option value="95">"Sheerness Health Centre"</option>
          <option value="96">"Monteagle Surgery"</option>
          <option value="97">"Chipping Norton Health Centre"</option>
          <option value="98">"Malthouse Surgery"</option>
          <option value="99">"St Peters Surgery"</option>
          <option value="100">"Colden Common"</option>
          <option value="101">"Park Surgery"</option>
          <option value="102">"Saxonbrook"</option>
          <option value="103">"Angmering Medical Centre"</option>
          <option value="104">"Kingswood Health Centre"</option>
          <option value="105">"Riverbank"</option>
          <option value="106">"Abbey Surgery, Tavistock"</option>
          <option value="107">"Exminster Limes Surgery"</option>
          <option value="108">"Exmouth Tennis Centre"</option>
          <option value="109">"Okehampton Medical Centre"</option>
          <option value="110">"Seaton"</option>
          <option value="111">"Heatherview Medical Centre"</option>
          <option value="112">"St Leonards Hospital"</option>
          <option value="113">"Stour Surgery"</option>
          <option value="114">"Carlyon Health Hub"</option>
          <option value="115">"Truro Health Park"</option>
          <option value="116">"Bodmin Treatment Centre"</option>
          <option value="117">"Club Batchwood"</option>
          <option value="118">"Barabara Castle Way Health Centre"</option>
          <option value="119">"Acorn Primary Health Care Centre"</option>
          <option value="120">"Orpington Health and Wellbeing Centre"</option>
          <option value="121">"St Margaret's Hospital"</option>
          <option value="122">"Lister Medical Centre"</option>
          <option value="123">"Westway Commuity Centre"</option>
          <option value="124">"Old Coulsdon Congregational Church"</option>
          <option value="125">"Minster Surgery"</option>
          <option value="126">"Swanscombe Health Centre"</option>
          <option value="127">"Jubilee Medical Centre"</option>
          <option value="128">"Cedar Medical Practice"</option>
          <option value="129">"Beacon Medical"</option>
          <option value="130">"Keepmoat Stadium"</option>
          <option value="131">"The Arts Centre, Queen Mary University"</option>
          <option value="132">"Forest Road Medical Centre"</option>
          <option value="133">"Elsdale Street Surgery"</option>
          <option value="134">"Carlton House"</option>
          <option value="135">"Wembley Centre for Health and Care"</option>
          <option value="136">"The Hive"</option>
          <option value="137">"Cathedral House"</option>
          <option value="138">"Redbridge Town Hall"</option>
          <option value="139">"Fullwell Cross Medical Centre"</option>
          <option value="140">"Sir James Hawkey Hall"</option>
          <option value="141">"Thetford Healthy Living Centre"</option>
          <option value="142">"Woolpit Health Centre"</option>
          <option value="143">"Health Innovation Centre, Lancaster Uni"</option>
          <option value="144">"Heath Lane Surgery"</option>
          <option value="145">"Priory Gardens Surgery"</option>
          <option value="146">"Len Valley Branch Surgery (Glebe)"</option>
          <option value="147">"Long Catlis Road Surgery"</option>
          <option value="148">"Oxford Centre"</option>
          <option value="149">"Village Surgery"</option>
          <option value="150">"Flagg Court Health Centre"</option>
          <option value="151">"Harborough Field Surgery"</option>
          <option value="152">"Weavers Medical"</option>
          <option value="153">"Woodsend Medical Centre"</option>
          <option value="154">"Kingsthorpe Medical Centre"</option>
          <option value="155">"Falkland Surgery"</option>
          <option value="156">"Temple Fortune Health Centre"</option>
          <option value="157">"Victoria Hospital (Raphael House)"</option>
          <option value="158">"Parsloes Surgery"</option>
          <option value="159">"Manor Park Medical Centre"</option>
          <option value="160">"St Johns Medical Centre"</option>
          <option value="161">"Plumstead Health Centre"</option>
          <option value="162">"Tessa Jowell Health Centre"</option>
          <option value="163">"Ware Drill Hall"</option>
          <option value="164">"Hertford Theatre"</option>
          <option value="165">"Seaham Primary Care Centre"</option>
          <option value="166">"Highlands Surgery"</option>
          <option value="167">"Bloomsbury Surgery"</option>
          <option value="168">"Bridgewater Surgeries"</option>
          <option value="169">"Castleford Civic Centre"</option>
          <option value="170">"IMWS Al-Hikmah Centre"</option>
          <option value="171">"Central Healthcare"</option>
          <option value="172">"Pickering Medical Practice"</option>
          <option value="173">"Hazelwood Practice"</option>
          <option value="174">"Whiteheath Medical Centre"</option>
          <option value="175">"Falcon Medical Centre"</option>
          <option value="176">"Monkspath Surgery"</option>
          <option value="177">"Combe Down Branch Surgery"</option>
          <option value="178">"The Gateway"</option>
          <option value="179">"West Mendip Community Hospital"</option>
          <option value="180">"Talbot Medical Centre"</option>
          <option value="181">"New Milton Health Centre"</option>
          <option value="182">"Preston Park Surgery"</option>
          <option value="183">"River Lodge Surgery"</option>
          <option value="184">"The Greenway Cntre"</option>
          <option value="185">"Pudding Pie Lane"</option>
          <option value="186">"Woodchurch Leisure Centre"</option>
          <option value="187">"Locke House"</option>
          <option value="188">"The Warwickshire (Golf Club)"</option>
          <option value="189">"Stratford Hospital"</option>
          <option value="190">"Kerseley Green Surgery"</option>
          <option value="191">"Pirelli Stadium, Burton Albion"</option>
          <option value="192">"Weymouth Community Hospital"</option>
          <option value="193">"Bridport Medical Centre"</option>
          <option value="194">"Rosebank Surgery"</option>
          <option value="195">"The Devereux Centre"</option>
          <option value="196">"Cheltenham East Community Fire Station"</option>
          <option value="197">"North Cotswolds Hospital"</option>
          <option value="198">"Heatherside Surgery"</option>
          <option value="199">"St Christopher's Church"</option>
          <option value="200">"Petersfield Festival Hall"</option>
          <option value="201">"Halo Leisure Centre"</option>
          <option value="202">"Ledbury Community Hall"</option>
          <option value="203">"Chertsey Hall"</option>
          <option value="204">"Aintree Community Centre"</option>
          <option value="205">"Valley Medical Centre"</option>
          <option value="206">"Maghull Town Hall"</option>
          <option value="207">"Huyton One Stop Shop"</option>
          <option value="208">"Hants Lane Clinic"</option>
          <option value="209">"Woodhouse Park Lifestyle Centre"</option>
          <option value="210">"Clarendon Leisure Centre"</option>
          <option value="211">"Park Royal Medical Practice"</option>
          <option value="212">"Number 1 Riverside"</option>
          <option value="213">"The Staddy"</option>
          <option value="214">"Kingston Crescent Surgery"</option>
          <option value="215">"Newport Medical Practice, Carisbrooke"</option>
          <option value="216">"Southport Centre for Health Wellbeing"</option>
          <option value="217">"Wargrave Surgery"</option>
          <option value="218">"Hampshire Court Hotel"</option>
          <option value="219">"The Hart Surgery"</option>
          <option value="220">"Christ Hospital - Blue Coats"</option>
          <option value="221">"The Glebe Surgery"</option>
          <option value="222">"Hyde Leisure Centre"</option>
          <option value="223">"Nonsuch Mansion"</option>
          <option value="224">"Devizes Corn Exchange"</option>
          <option value="225">"Rowden Medical Partnership"</option>
          <option value="226">"Steam Museum"</option>
          <option value="227">"Badger Farm Community Centre"</option>
          <option value="228">"Bursledon Surgery"</option>
          <option value="229">"County Showground"</option>
          <option value="230">"Balham Health Centre"</option>
          <option value="231">"Essex House Surgery"</option>
          <option value="232">"Mulberry Centre"</option>
          <option value="233">"St Bonafice"</option>
          <option value="234">"English Riveria Centre"</option>
          <option value="235">"Heart of Hounslow Centre for Health"</option>
          <option value="236">"Richford Gate Medical Centre"</option>
          <option value="237">"Altrinham Health and Wellbeing Hub"</option>
          <option value="238">"Orford Jubilee Hub"</option>
          <option value="239">"Frodsham Leisure Centre"</option>
          <option value="240">"DCBL Stadium"</option>
          <option value="241">"Totally Wicked Stadium, St Helens RLFC"</option>
          <option value="242">"Robin Park Leisure Centre"</option>
          <option value="243">"Codsall Satelite Clinic"</option>
          <option value="244">"Salt Hill Activity Centre"</option>
          <option value="245">"Epsom Racecourse"</option>
          <option value="246">"Brasshouse Community Centre"</option>
          <option value="247">"All Saints Medical Centre"</option>
          <option value="248">"Erdington Medical Centre"</option>
          <option value="249">"The Church of the Latter Day Saints"</option>
          <option value="250">"Stubley Medical Centre"</option>
          <option value="251">"Revival Fires"</option>
          <option value="252">"Hume Street Medical Centre"</option>
          <option value="253">"Prospect View Medical Centre"</option>
          <option value="254">"Turnpike House"</option>
          <option value="255">"Winyates Health Centre"</option>
          <option value="256">"Market Harborough MC"</option>
          <option value="257">"Humberstone Medical Centre"</option>
          <option value="258">"Danetre Medical Practice"</option>
          <option value="259">"Longton Health Centre"</option>
          <option value="260">"Mossgreen Surgery"</option>
          <option value="261">"Birchenwood Sports Centre"</option>
          <option value="262">"JCB Compact Products"</option>
          <option value="263">"Darlaston HC"</option>
          <option value="264">"Mayfield Medical Practice Branch"</option>
          <option value="265">"Balsall Common Health Centre"</option>
          <option value="266">"St Heliers Medical Practice"</option>
          <option value="267">"Portway Lifestyle Centre"</option>
          <option value="268">"Hall Green HC"</option>
          <option value="269">"Brierley Hill Methodist Church, Bank St"</option>
          <option value="270">"Droitwich Health Centre"</option>
          <option value="271">"Larruperz Centre"</option>
          <option value="272">"Quay House Surgery"</option>
          <option value="273">"Fosse Medical Centre"</option>
          <option value="274">"Sturdee Road Health and Wellbeing Centre"</option>
          <option value="275">"Cliff Villages Medical Practice"</option>
          <option value="276">"Kings Heath Centre"</option>
          <option value="277">"Loomer Road Surgery"</option>
          <option value="278">"Chasetown Medical Centre"</option>
          <option value="279">"Michelin MAC Sports and Conference Facility"</option>
          <option value="280">"Woodcross MC"</option>
          <option value="281">"The Oaks Medical Practice"</option>
          <option value="282">"Church Farm Ripley"</option>
          <option value="283">"Audley Mills Surgery"</option>
          <option value="284">"St Nicholas Health Centre"</option>
          <option value="285">"Bishops Stortford Football Club"</option>
          <option value="286">"Manor View Practice"</option>
          <option value="287">"Bushmead Medical Centre"</option>
          <option value="288">"Westcroft Health Centre"</option>
          <option value="289">"Cringleford Surgery"</option>
          <option value="290">"The Nevendon Centre"</option>
          <option value="291">"Stockwell Lodge Medical Centre-Annexe site"</option>
          <option value="292">"Roebuck Surgery"</option>
          <option value="293">"Attenborough Surgery"</option>
          <option value="294">"Ivry Street Medical Practice"</option>
          <option value="295">"Maldon District Council Offices"</option>
          <option value="296">"Valkyrie Primary Care Centre"</option>
          <option value="297">"Lord Butler Lesiure Centre"</option>
          <option value="298">"Wentworth Medical Practice"</option>
          <option value="299">"Evergreen Surgery"</option>
          <option value="300">"Hanley Primary Care Centre"</option>
          <option value="301">"Hampton Wick Surgery"</option>
          <option value="302">"Beckenham Beacon"</option>
          <option value="303">"Young People Centre"</option>
          <option value="304">"South Westminster Centre for Health"</option>
          <option value="305">"Ealing Town Hall"</option>
          <option value="306">"Winchmore Hill Practice"</option>
          <option value="307">"Bounds Green Group Practice"</option>
          <option value="308">"Gosbury Hill Surgery"</option>
          <option value="309">"Artesian Building"</option>
          <option value="310">"Queen Marys Hospital"</option>
          <option value="311">"Belsize Priory Health Centre"</option>
          <option value="312">"Barton Neighbourhood Centre"</option>
          <option value="313">"South Bar House"</option>
          <option value="314">"Royal South Hants Hospital"</option>
          <option value="315">"Swallowfield Surgery"</option>
          <option value="316">"East Oxford Health Centre"</option>
          <option value="317">"Farnham Centre for Health"</option>
          <option value="318">"Brune Medical Centre"</option>
          <option value="319">"Solent View Medical Practice"</option>
          <option value="320">"West Wight Sport and Social Centre"</option>
          <option value="321">"Eastney Health Centre"</option>
          <option value="322">"Chessel Avenue Surgery"</option>
          <option value="323">"Park Surgery"</option>
          <option value="324">"AFC Totton"</option>
          <option value="325">"Charing Surgery"</option>
          <option value="326">"Meopham Medical Centre"</option>
          <option value="327">"Springhead Health Ltd"</option>
          <option value="328">"The Orchard Practice"</option>
          <option value="329">"Canon Building"</option>
          <option value="330">"Adelaide Health Centre"</option>
          <option value="331">"Woodley Centre Surgery"</option>
          <option value="332">"Jericho Health Centre"</option>
          <option value="333">"Brook Lane Surgery"</option>
          <option value="334">"Portchester Practice"</option>
          <option value="335">"Waterlooville Health Centre"</option>
          <option value="336">"Cosham Health Centre"</option>
          <option value="337">"Lake Road Health Centre"</option>
          <option value="338">"Ladies Walk Surgery"</option>
          <option value="339">"Avicenna Medical Centre"</option>
          <option value="340">"Greensands Branch Surgery (Loose)"</option>
          <option value="341">"Musgrove Park Medical Centre"</option>
          <option value="342">"Woodlands Family Practice"</option>
          <option value="343">"Emberbrook Surgery"</option>
          <option value="344">"Beacon Shopping Centre"</option>
          <option value="345">"East trees health centre"</option>
          <option value="346">"Clare House"</option>
          <option value="347">"Falmouth Health Centre"</option>
          <option value="348">"East Way Clinic"</option>
          <option value="349">"Frome Medical Centre"</option>
          <option value="350">"Clifton College Preparatory School Hall"</option>
          <option value="351">"Horfield Health Centre"</option>
          <option value="352">"West Walk Surgery"</option>
          <option value="353">"Churchdown Community Centre"</option>
          <option value="354">"Ramsbury Surgery"</option>
          <option value="355">"Minehead Community Hospital"</option>
          <option value="356">"Redruth Health Clinic"</option>
          <option value="357">"Pavillions"</option>
          <option value="358">"Holsworthy Medical Centre"</option>
          <option value="359">"Narrowcliff Surgery"</option>
          <option value="360">"Beaufort Rd Surgery"</option>
          <option value="361">"Westbourne Medical centre"</option>
          <option value="362">"St Leonards Medical Practice"</option>
          <option value="363">"Marksbury Road"</option>
          <option value="364">"Brockway Medical Centre"</option>
          <option value="365">"Rowcroft Medical Centre"</option>
          <option value="366">"The White Horse Health Centre,"</option>
          <option value="367">"Mere Lane Health Centre"</option>
          <option value="368">"Victoria Central Hospital"</option>
          <option value="369">"The Brindley"</option>
          <option value="370">"The Oval Leisure Centre"</option>
          <option value="371">"South Reddish Medical Centre"</option>
          <option value="372">"Leigh Leisure Centre"</option>
          <option value="373">"Geoffrey Street Health Centre"</option>
          <option value="374">"Waters Green Medical Centre"</option>
          <option value="375">"Stamford House"</option>
          <option value="376">"Fields New Road Primary Care Centre"</option>
          <option value="377">"Life Centre"</option>
          <option value="378">"Morecambe Football Club, Mazuma Arena"</option>
          <option value="379">"Dunstan Village"</option>
          <option value="380">"West Stand , Halliwell Jones Stadium"</option>
          <option value="381">"Bealeys Community Hospital"</option>
          <option value="382">"Manchester Rugby Club, Cheadle Hulme"</option>
          <option value="383">"Birleywood Health Centre"</option>
          <option value="384">"Yarnspinners PHCC"</option>
          <option value="385">"Lever Chambers"</option>
          <option value="386">"Royton Health and Well Being Centre"</option>
          <option value="387">"Partington Health Centre"</option>
          <option value="388">"Davyhulme Medical Centre"</option>
          <option value="389">"Bartholemew Medical Practice"</option>
          <option value="390">"Pilgrim Primary Care Centre"</option>
          <option value="391">"Riverside Surgery"</option>
          <option value="392">"Richardson Community Hospital"</option>
          <option value="393">"Hartlepool Town Hall"</option>
          <option value="394">"Victoria Medical Centre"</option>
          <option value="395">"St Andrews Medical Practice, Oxford Road site"</option>
          <option value="396">"Bunnyhill PCCC"</option>
          <option value="397">"Peterlee Health Centre"</option>
          <option value="398">"Priory View Medical Centre"</option>
          <option value="399">"Kippax Health Centre"</option>
          <option value="400">"Bramley Village Health and Wellbeing Centre"</option>
          <option value="401">"Alwoodley Medical Centre"</option>
          <option value="402">"Scartho Medical Centre"</option>
          <option value="403">"The Forum"</option>
          <option value="404">"Claypath & University Medical Group"</option>
          <option value="405">"Auckland Medical Group"</option>
          <option value="406">"Brandon lane Surgery building"</option>
          <option value="407">"Ashington Cricket Club"</option>
          <option value="408">"Railway Medical Group"</option>
          <option value="409">"Woodroyd Medical Practice"</option>
          <option value="410">"The Grange Medical Centre"</option>
          <option value="411">"Bridge street"</option>
          <option value="412">"Barkerend Health Centre"</option>
          <option value="413">"Shipley Health Centre"</option>
          <option value="414">"Stamford House"</option>
          <option value="415">"Colchester Primary Care Centre"</option>
          <option value="416">"Emmanuel Archer Hall"</option>
          <option value="417">"Terrington St Johns Surgery"</option>
          <option value="418">"Watford Health Centte"</option>
          <option value="419">"Buckhurst Way Clinic"</option>
          <option value="420">"Hornchurch Library"</option>
          <option value="421">"Keston Medical Practice"</option>
          <option value="422">"St Barnabas Church"</option>
          <option value="423">"Earls Court Health and Wellbeing Centre"</option>
          <option value="424">"Atherstone Surgery"</option>
          <option value="425">"Charnwood Borough Council Offices"</option>
          <option value="426">"Community HC"</option>
          <option value="427">"Furlong Medical Centre"</option>
          <option value="428">"Keats Grove Surgery"</option>
          <option value="429">"Lisle Court Medical Centre"</option>
          <option value="430">"Long Eaton Health Centre"</option>
          <option value="431">"Melton Sports Village"</option>
          <option value="432">"Newholme hospital"</option>
          <option value="433">"Oadby Racecourse"</option>
          <option value="434">"Polesworth HC"</option>
          <option value="435">"Rutland Health"</option>
          <option value="436">"Sycamore House"</option>
          <option value="437">"Kilton Community Centre"</option>
          <option value="438">"Adwick Leisure Centre"</option>
          <option value="439">"Alf Marshall Community Centre"</option>
          <option value="440">"Apollo Court Medical Centre"</option>
          <option value="441">"Bankfield Surgery"</option>
          <option value="442">"Beeston Village"</option>
          <option value="443">"Blaydon Primary Care Centre"</option>
          <option value="444">"Brockwell Medical Group"</option>
          <option value="445">"Castlegate and Derwent Surgery"</option>
          <option value="446">"Darnall PCC"</option>
          <option value="447">"Dearne Valley Group Practice"</option>
          <option value="448">"Dearne Valley Leisure Centre"</option>
          <option value="449">"East Leeds Health Centre"</option>
          <option value="450">"Fairlawns"</option>
          <option value="451">"Felling Hub "</option>
          <option value="452">"Holme Valley Memorial Hospital"</option>
          <option value="453">"Houghton Primary care Centre"</option>
          <option value="454">"Kilton Forest Community Centre"</option>
          <option value="455">"King's Medical Practice"</option>
          <option value="456">"Langdale Centre"</option>
          <option value="457">"Montgomery Hall"</option>
          <option value="458">"Newcastle Eagles Basketball"</option>
          <option value="459">"Nimbuscare Mass Vaccination Hub"</option>
          <option value="460">"North Ormesby Branch - Linthorpe Surgery"</option>
          <option value="461">"Nursery Lane Medical Centre"</option>
          <option value="462">"Oakwood Lane Medical Practice"</option>
          <option value="463">"Open Door"</option>
          <option value="464">"Penrith Hospital"</option>
          <option value="465">"Posterngate Surgery"</option>
          <option value="466">"Rotherham Leisure Centre"</option>
          <option value="467">"Sandal RUFC"</option>
          <option value="468">"Tadcaster Health Centre"</option>
          <option value="469">"Tennants Auction House"</option>
          <option value="470">"The Flowers Health Centre"</option>
          <option value="471">"The Glen Primary Care Centre"</option>
          <option value="472">"The Parks Leisure Centre"</option>
          <option value="473">"The Pavillion"</option>
          <option value="474">"The Ridge"</option>
          <option value="475">"Todmorden Group Practice"</option>
          <option value="476">"Washington PCC"</option>
          <option value="477">"Wetherby Health Centre (LCH)"</option>
          <option value="478">"Whitby Pavillion"</option>
          <option value="479">"Wigton Community Hospital"</option>
          <option value="480">"Yeadon Health Centre"</option>
          <option value="481">"Buckshaw Village Surgery"</option>
          <option value="482">"Burscough Health Centre"</option>
          <option value="483">"Captain French Surgery"</option>
          <option value="484">"Colne Health Centre Pharmacy"</option>
          <option value="485">"Darwen Health Centre"</option>
          <option value="486">"Delamere Medical Practice"</option>
          <option value="487">"Denton Festival Hall"</option>
          <option value="488">"Garstang Medical Practice"</option>
          <option value="489">"Glossop Cricket  & Bowling Club"</option>
          <option value="490">"Lee Jones Centre (Vauxhall Health Centre)"</option>
          <option value="491">"Lockwood GP Surgery"</option>
          <option value="492">"Moreton Cross Group Practice"</option>
          <option value="493">"Over Wyre Medical Centre"</option>
          <option value="494">"Penwortham Cricket Club"</option>
          <option value="495">"Pike Medical Practice, Market Street, Mossley, Tameside"</option>
          <option value="496">"Townsend Health Centre"</option>
          <option value="497">"Boathouse Surgery/Rosewood Hall"</option>
          <option value="498">"Bower Mount Medical Centre"</option>
          <option value="499">"Bridge Health Centre"</option>
          <option value="500">"Circuit Lane Surgery"</option>
          <option value="501">"Crosfield Hall"</option>
          <option value="502">"Desborough Suite"</option>
          <option value="503">"Emsworth Baptist Church"</option>
          <option value="504">"Estuary View Medical Centre"</option>
          <option value="505">"Faversham Health Centre"</option>
          <option value="506">"Fordingbridge Hospital"</option>
          <option value="507">"Forest Surgery"</option>
          <option value="508">"Hampden Park"</option>
          <option value="509">"Hayling Island Health Centre"</option>
          <option value="510">"McLaren"</option>
          <option value="511">"Milford on Sea War Memorial Hospital"</option>
          <option value="512">"Nordon House Surgery, Clinical Centre"</option>
          <option value="513">"Oaklands Health Centre"</option>
          <option value="514">"Princess Park Health Centre"</option>
          <option value="515">"Risborough Community Centre"</option>
          <option value="516">"The Bay Medical Practice"</option>
          <option value="517">"The Leys Health Centre"</option>
          <option value="518">"The Lights"</option>
          <option value="519">"University Medical Centre"</option>
          <option value="520">"Waitrose Sports Hall"</option>
          <option value="521">"Wallingford Community Hospital"</option>
          <option value="522">"Westridge Centre"</option>
          <option value="523">"Winchester Holiday Inn"</option>
          <option value="524">"Windrush Health Centre"</option>
          <option value="525">"Windsor Racecourse"</option>
          <option value="526">"Beeches Green Health Centre"</option>
          <option value="527">"Christchurch Medical Centre"</option>
          <option value="528">"Cinderford Health Centre"</option>
          <option value="529">"Cirencester Hospital"</option>
          <option value="530">"Dawlish Community Hospital"</option>
          <option value="531">"Glenside Surgery"</option>
          <option value="532">"Portishead Medical Group"</option>
          <option value="533">"Shirehampton Group Practice"</option>
          <option value="534">"Spencers Sports and Social Club"</option>
          <option value="535">"Shape Mendip"</option>
          <option value="536">"North Petherton Rugby Club"</option>
          <option value="537">"Barnstaple Leisure"</option>
          <option value="538">"Mount Pleasant Health Centre"</option>
          <option value="539">"Morland House"</option>
          <option value="540">"Pulborough Medical Group"</option>
          <option value="541">"Ninfield Surgery"</option>
          <option value="542">"Perrymount Road"</option>
          <option value="543">"Leacroft Medical Practice"</option>
          <option value="544">"Harborne Medical Practice"</option>
          <option value="545">"Richmond Medical Centre"</option>
          <option value="546">"River Brook Medical Centre"</option>
          <option value="547">"Saltley Health Centre"</option>
          <option value="548">"Washwood Heath Health Centre"</option>
          <option value="549">"Kingswinford Community Centre"</option>
          <option value="550">"Stourbridge National Spiritualist Church"</option>
          <option value="551">"Saxon Hall"</option>
          <option value="552">"Old school Surgery"</option>
          <option value="553">"St Mary's Medical Centre"</option>
          <option value="554">"Brackley Medical Centre"</option>
          <option value="555">"Moulton Community Centre"</option>
          <option value="556">"Christchurch MC"</option>
          <option value="557">"Lakeside Cottingham Road Surgery"</option>
          <option value="558">"Teldoc, Malinslee"</option>
          <option value="559">"The Paddocks Community Centre"</option>
          <option value="560">"North Brink Practice"</option>
          <option value="561">"Stanground Surgery"</option>
          <option value="562">"Holy Trinity R C Parish"</option>
          <option value="563">"George Hurd Centre"</option>
          <option value="564">"Peckwater Centre"</option>
          <option value="565">"Oaklodge Medical Centre"</option>
          <option value="566">"St. Charles Centre for Health and Wellbeing"</option>
          <option value="567">"Valley Park Surgery"</option>
          <option value="568">"Alnwick Cricket Club"</option>
          <option value="569">"Coquet Medical Group"</option>
          <option value="570">"Kirkburton Health Centre"</option>
          <option value="571">"Low Grange Health Village"</option>
          <option value="572">"Marsh House Medical Practice"</option>
          <option value="573">"Newcastle Racecourse"</option>
          <option value="574">"Ponteland Medical Group"</option>
          <option value="575">"Redcar Primary Care Hospital"</option>
          <option value="576">"Riverside Medical Practice"</option>
          <option value="577">"Shiremoor Resource Centre"</option>
          <option value="578">"The Sele Medical Practice"</option>
          <option value="579">"Thornaby & Barwick Medical Group"</option>
          <option value="580">"Thorntree Surgery"</option>
          <option value="581">"Well Close Medical Group"</option>
          <option value="582">"Lunesdale Surgery"</option>
          <option value="583">"Gorton Street"</option>
          <option value="584">"South Shore Primary Care Centre"</option>
          <option value="585">"The Ryan Medical Centre"</option>
          <option value="586">"Rawtenstall Primary Health Care Centre - Rawtenstall"</option>
          <option value="587">"Clitheroe Health Centre"</option>
          <option value="588">"Elizabethan Suite"</option>
          <option value="589">"Shay Lane Medical Centre"</option>
          <option value="590">"Kepple Building"</option>
          <option value="591">"Phoenix Centre"</option>
          <option value="592">"Batheaston Medical Center"</option>
          <option value="593">"Wingfield Surgery"</option>
          <option value="594">"Somer Centre"</option>
          <option value="595">"Stockwood Medical Centre"</option>
          <option value="596">"Severnview Family Practice"</option>
          <option value="597">"Concord Medical Centre"</option>
          <option value="598">"Sturminster Newton Medical Centre"</option>
          <option value="599">"The Blandford group Practice"</option>
          <option value="600">"Digby Hall"</option>
          <option value="601">"Malmesbury Primary Care Centre"</option>
          <option value="602">"Northlands Surgery"</option>
          <option value="603">"Michael Herbert Hall"</option>
          <option value="604">"Tidworth Leisure Centre"</option>
          <option value="605">"The Meadows"</option>
          <option value="606">"St Clare's Medical Centre"</option>
          <option value="607">"Mount Hawke"</option>
          <option value="608">"Khattak HUB"</option>
          <option value="609">"Greenridge Surgery"</option>
          <option value="610">"Bath Row Medical Practice"</option>
          <option value="611">"Cavendish Medical Practice"</option>
          <option value="612">"City Hospital - Cardiac Rehab Gym"</option>
          <option value="613">"Poplars Surgery"</option>
          <option value="614">"Iridium Medical Practice"</option>
          <option value="615">"Kingstanding Circle Surgery"</option>
          <option value="616">"BHI Parkside"</option>
          <option value="617">"Lyng Community Centre"</option>
          <option value="618">"Studley Village Hall"</option>
          <option value="619">"Yardley Green Medical Centre"</option>
          <option value="620">"Priory Gate Practice"</option>
          <option value="621">"Coventry and North Warwickshire Cricket Club"</option>
          <option value="622">"Hastings House Medical Centre"</option>
          <option value="623">"Derby Arena"</option>
          <option value="624">"Babington Hospital"</option>
          <option value="625">"St Oswalds Hospital"</option>
          <option value="626">"Thorpe Astley"</option>
          <option value="627">"Portland Medical Practice"</option>
          <option value="628">"Rustons Sports and Social Club"</option>
          <option value="629">"Ashfield Health & Wellbeing Centre"</option>
          <option value="630">"Gamston Community Hall"</option>
          <option value="631">"Richard Herrod Leisure Centre"</option>
          <option value="632">"Cripps Medical Cntre"</option>
          <option value="633">"Grange Park Primary Care Centre"</option>
          <option value="634">"Mawsley Medical Centre"</option>
          <option value="635">"Western favell HC"</option>
          <option value="636">"Whitefields Surgery"</option>
          <option value="637">"The Sidings Medical Practice"</option>
          <option value="638">"Franklin Hall Spilsby"</option>
          <option value="639">"Sharley Park Leisure Centre"</option>
          <option value="640">"Thornbrook Surgery"</option>
          <option value="641">"Hanley Health Centre"</option>
          <option value="642">"Park Medical Centre"</option>
          <option value="643">"Horsefair Practice Group Hillsprings Surgery"</option>
          <option value="644">"Forrester Street Surgery"</option>
          <option value="645">"Bloxwich Active Living Centre"</option>
          <option value="646">"Oak Park Leisure Centre"</option>
          <option value="647">"Alfred Squire Road HC"</option>
          <option value="648">"Keys Medical Centre"</option>
          <option value="649">"Whitmore Reans HC"</option>
          <option value="650">"City Walls Medical Centre"</option>
          <option value="651">"Cheshire View."</option>
          <option value="652">"Neston Medical Centre"</option>
          <option value="653">"Dental Suite in Eagle Bridge Health & Wellbeing Centre,"</option>
          <option value="654">"Apollo Buckingham Health Sciences Campus Ltd"</option>
          <option value="655">"Congleton Town Hall"</option>
          <option value="656">"Nantwich Civic Hall"</option>
          <option value="657">"Kingsmead Medical Centre"</option>
          <option value="658">"Speke Neighbourhood Health Centre"</option>
          <option value="659">"Kensington Park General Practice (Kensington Portakabin)"</option>
          <option value="660">"Grange Health Centre"</option>
          <option value="661">"Carnforth Clinic ground floor"</option>
          <option value="662">"Little Thornton Theatre"</option>
          <option value="663">"Middleton Health Centre"</option>
          <option value="664">"Newton Heath Health Centre"</option>
          <option value="665">"Moorside"</option>
          <option value="666">"Jubilee House"</option>
          <option value="667">"Clayton Brook Clinic"</option>
          <option value="668">"Ainsdale HWB Centre"</option>
          <option value="669">"Bosden Moor Surgery"</option>
          <option value="670">"Heald Green Village Hall"</option>
          <option value="671">"Bredbury Medical Centre"</option>
          <option value="672">"Wilmslow Health Centre"</option>
          <option value="673">"Site 2 - The 13 Club"</option>
          <option value="674">"Knutsford District Community Hospital"</option>
          <option value="675">"Bellingham Common Room, University of Hertfordshire Education Corporation"</option>
          <option value="676">"Dacorum Locality"</option>
          <option value="677">"Medici Medical Centre"</option>
          <option value="678">"Oakridge Medical Centre"</option>
          <option value="679">"Central MK Medical Practice"</option>
          <option value="680">"Kings House"</option>
          <option value="681">"Park Surgery"</option>
          <option value="682">"Bowthorpe Health Centre"</option>
          <option value="683">"Dumbelton Medical Centre"</option>
          <option value="684">"Courtenay House Surgery (part of Bancroft Medical Centre)"</option>
          <option value="685">"Allum Hall"</option>
          <option value="686">"Low Moor"</option>
          <option value="687">"Whetley Medical Centre"</option>
          <option value="688">"Windhill Green Emerald Suite"</option>
          <option value="689">"Orchard House Surgery"</option>
          <option value="690">"Maryport Rugby Club"</option>
          <option value="691">"Morton Branch Surgery"</option>
          <option value="692">"Brampton Community Centre (priority 1)"</option>
          <option value="693">"PELTON & FELLROSE MEDICAL GROUP"</option>
          <option value="694">"Bowburn Community Centre"</option>
          <option value="695">"Feethams House"</option>
          <option value="696">"NORTH HOUSE SURGERY"</option>
          <option value="697">"THE CENTRAL SURGERY BARTON"</option>
          <option value="698">"Retford Hospital Outpatients Department"</option>
          <option value="699">"Thorne Leisure Centre"</option>
          <option value="700">"SOUTH AXHOLME PRACTICE"</option>
          <option value="701">"Willerby Hill"</option>
          <option value="702">"Beverley Race Course"</option>
          <option value="703">"Northowram Surgery"</option>
          <option value="704">"Lingwell Croft"</option>
          <option value="705">"Shenstone House Surgery"</option>
          <option value="706">"Woodhouse Health Centre"</option>
          <option value="707">"The Bede Centre"</option>
          <option value="708">"RAWLING RD"</option>
          <option value="709">"St Columbus Church (priority 1)"</option>
          <option value="710">"Porter Brook Medical Centre"</option>
          <option value="711">"Dore Surgery"</option>
          <option value="712">"The Mathews Practice (priority 1)"</option>
          <option value="713">"Burncross"</option>
          <option value="714">"Valley Medical Centre"</option>
          <option value="715">"Rawmarsh Customer Service Centre"</option>
          <option value="716">"Oak House"</option>
          <option value="717">"Meadowgreen Health Centre"</option>
          <option value="718">"Newgate Practice"</option>
          <option value="719">"Riverview Health Centre"</option>
          <option value="720">"Peterlee Health Centre"</option>
          <option value="721">"THORNABY & BARWICK MEDICAL GROUP"</option>
          <option value="722">"MARSH HOUSE MEDICAL PRACTICE"</option>
          <option value="723">"Medical Centre Bridlington - practice 3"</option>
          <option value="724">"Alfred Bean Hospital"</option>
          <option value="725">"Langley Health Centre"</option>
          <option value="726">"University Health Service"</option>
          <option value="727">"County Oak Medical"</option>
          <option value="728">"Strand Medical Group"</option>
          <option value="729">"Durrington Health Centre"</option>
          <option value="730">"Portslade Health Centre"</option>
          <option value="731">"Northbourne Medical Centre"</option>
          <option value="732">"Northgate Medical Practice"</option>
          <option value="733">"Building A, Fleet Health Campus"</option>
          <option value="734">"Princes Hall"</option>
          <option value="735">"Southwood Practice"</option>
          <option value="736">"Adams Park"</option>
          <option value="737">"Chesham Town Hall"</option>
          <option value="738">"Lordswood HLC"</option>
          <option value="739">"Kennington Health CeNotre"</option>
          <option value="740">"Didcot Civic Hall"</option>
          <option value="741">"Wantage Health Centre"</option>
          <option value="742">"Clifton Hampden Village Hall"</option>
          <option value="743">"Cherwell School"</option>
          <option value="744">"Building 139, The Command Works, Bicester Heritage"</option>
          <option value="745">"Islip Villiage Hall"</option>
          <option value="746">"Bognor Medical Centre"</option>
          <option value="747">"Southsea Medical Centre"</option>
          <option value="748">"Wokingham Medical Centre / Bradbury Centre"</option>
          <option value="749">"Chalfont Surgery / Salvation Army Hall"</option>
          <option value="750">"Holmhurst Surgery"</option>
          <option value="751">"Pound Hill Medical Group"</option>
          <option value="752">"Medwyn Surgery"</option>
          <option value="753">"Centenary Hall"</option>
          <option value="754">"Tandridge District Council"</option>
          <option value="755">"Sevenoaks Medical Centre"</option>
          <option value="756">"St Stephens Medical Centre"</option>
          <option value="757">"The Kings Church, Hastings"</option>
          <option value="758">"Hythe Centre"</option>
          <option value="759">"Parkway Health Centre"</option>
          <option value="760">"Westwood Mason Hall"</option>
          <option value="761">"Erith Health Centre"</option>
          <option value="762">"Oliver Road Polyclinic"</option>
          <option value="763">"Essex Lodge"</option>
          <option value="764">"St Edmunds Church"</option>
          <option value="765">"Tithe Farm Sports & Social Club"</option>
          <option value="766">"Watling Medical Centre"</option>
          <option value="767">"Lane End Medical Group"</option>
          <option value="768">"The Waldron Health Centre"</option>
          <option value="769">"Upper Floor, The Jenner Health Centre"</option>
          <option value="770">"Charlton House"</option>
          <option value="771">"Oxleas NHS Foundation Trust, Wensley Close"</option>
          <option value="772">"The Junction Health Centre"</option>
          <option value="773">"1st East Putney Scout Hut"</option>
          <option value="774">"Trevelyan House Surgery"</option>
          <option value="775">"Brocklebank Health Centre"</option>
          <option value="776">"Streatham Place Surgery"</option>
          <option value="777">"The Nelson Health Centre"</option>
          <option value="778">"Violet Melchett"</option>
          <option value="779">"York Medical Centre"</option>
          <option value="780">"Acorn Group Practice"</option>
          <option value="781">"Parkshot Medical Practice"</option>
          <option value="782">"The Dominion Centre"</option>
          <option value="783">"Chiswick Health Centre"</option>
          <option value="784">"Lords Cricket Ground"</option>
          <option value="785">"Wincanton Community Hospital"</option>
          <option value="786">"COVID Vaccine Clinic"</option>
          <option value="787">"Wareham Hospital"</option>
          <option value="788">"Marine & Oakridge Pship"</option>
          <option value="789">"Fishponds Family Practice"</option>
          <option value="790">"West View Surgery"</option>
          <option value="791">"Knowle West Healthy Living Centre"</option>
          <option value="792">"Lodgeside Surgery"</option>
          <option value="793">"Steam"</option>
          <option value="794">"Pewsey Surgery"</option>
          <option value="795">"Salisbury Cathedral"</option>
          <option value="796">"Salisbury Plain Health Centre, Larkhill"</option>
          <option value="797">"Pensilva Health Centre"</option>
          <option value="798">"The Atrium Healthth Centre"</option>
          <option value="799">"Culm Valley Integrated Centre for Health"</option>
          <option value="800">"Lords Meadow Leisure Centre"</option>
          <option value="801">"St Thomas Health Centre"</option>
          <option value="802">"College Way Surgery"</option>
          <option value="803">"Wellington Community Hospital"</option>
          <option value="804">"Sherborne House"</option>
          <option value="805">"Helston Medical Centre"</option>
          <option value="806">"Redruth Health Centre"</option>
          <option value="807">"Bodriggy Surgery"</option>
          <option value="808">"WoodGate Valley Practice"</option>
          <option value="809">"Harlequin Surgery"</option>
          <option value="810">"Coton Centre"</option>
          <option value="811">"Broomfield Park Medical Centre"</option>
          <option value="812">"Abbeygate Shopping Centre (Unit 6)"</option>
          <option value="813">"Bedworth Civic Hall"</option>
          <option value="814">"Quinton Park Medical Centre"</option>
          <option value="815">"Royal Leamington Spa Rehabilitation Hospital"</option>
          <option value="816">"Tile Hill Primary Care Centre"</option>
          <option value="817">"Southam Clinic"</option>
          <option value="818">"Holbrooks Health Team"</option>
          <option value="819">"Oaklands Village and Community Care Centre"</option>
          <option value="820">"Measham Leisure Centre"</option>
          <option value="821">"Littlewick"</option>
          <option value="822">"John Coupland Hospital"</option>
          <option value="823">"Kidderminster Medical Centre"</option>
          <option value="824">"Hinckley Leisure Centre"</option>
          <option value="825">"St Peters Health Centre"</option>
          <option value="826">"Merridale Medical Centre"</option>
          <option value="827">"Peepul Centre"</option>
          <option value="828">"Marisco Medical Practice"</option>
          <option value="829">"Lincolnshire Showground"</option>
          <option value="830">"Shirebrook Leisure Centre"</option>
          <option value="831">"Joe Hallam Suite, Newark Showground"</option>
          <option value="832">"Kings Meadow"</option>
          <option value="833">"Springfields Events and Conference Centre"</option>
          <option value="834">"The Storehouse Skegness"</option>
          <option value="835">"The Winding Wheel"</option>
          <option value="836">"The Springs Health Centre"</option>
          <option value="837">"Roman Way Hotel"</option>
          <option value="838">"Lichfield Cathedral"</option>
          <option value="839">"St Pauls Church"</option>
          <option value="840">"Newcastle Under Lyme College"</option>
          <option value="841">"Biddulph Town Hall"</option>
          <option value="842">"Buxton Medical Practice"</option>
          <option value="843">"Ramsbottom Civic Hall"</option>
          <option value="844">"Avondale Health Centre"</option>
          <option value="845">"Wwaters Meeting Health Centre"</option>
          <option value="846">"Breightmet Health Centre"</option>
          <option value="847">"Peter House Surgery"</option>
          <option value="848">"St Columba:"</option>
          <option value="849">"Ellesmere Port Civic Hall"</option>
          <option value="850">"ICC"</option>
          <option value="851">"Lowfield Surgery"</option>
          <option value="852">"Hazel Grove Baptist Church"</option>
          <option value="853">"St Peter's Pavillion"</option>
          <option value="854">"Golborne Parkside Sports & Community Club"</option>
          <option value="855">"Site 1 - Victoria Hall,"</option>
          <option value="856">"West Derby Medical Centre"</option>
          <option value="857">"North Park  Health Centre N84019"</option>
          <option value="858">"One Stop Shop - Kirkby"</option>
          <option value="859">"Bousfield Surgery"</option>
          <option value="860">"Parkview Medical Centre"</option>
          <option value="861">"Ulverston Community Health Centre"</option>
          <option value="862">"Waterloo House Surgery"</option>
          <option value="863">"The Grange Community Centre"</option>
          <option value="864">"Jain Community Centre"</option>
          <option value="865">"The Vallance Centre"</option>
          <option value="866">"Chancellor's Hotel"</option>
          <option value="867">"Little Hulton Library"</option>
          <option value="868">"Eccles Recreation / Leisure Centre"</option>
          <option value="869">"Irlam and Cadishead Recreation / Leisure Centre"</option>
          <option value="870">"The Irish Community Centre"</option>
          <option value="871">"Civic Centre,"</option>
          <option value="872">"Harpenden Public Halls"</option>
          <option value="873">"Cornford House Surgery"</option>
          <option value="874">"Granta Medical Practices"</option>
          <option value="875">"Huntingdon Road Surgery"</option>
          <option value="876">"The Epicentre"</option>
          <option value="877">"Rivermead Gate Medical Practice"</option>
          <option value="878">"Melbourne House Surgery"</option>
          <option value="879">"Whitley House Surgery"</option>
          <option value="880">"Crouch Vale Medical Centre"</option>
          <option value="881">"St Michaels Hospital"</option>
          <option value="882">"Fern House Surgery"</option>
          <option value="883">"Cornard Surgery"</option>
          <option value="884">"Lavenham Branch Surgery"</option>
          <option value="885">"Fryatt Hospital"</option>
          <option value="886">"Pump House Surgery"</option>
          <option value="887">"Constable Country Medical Practice"</option>
          <option value="888">"Halsey Hall"</option>
          <option value="889">"The Grove Medical Centre"</option>
          <option value="890">"Woodbridge Community Hall"</option>
          <option value="891">"The Mix"</option>
          <option value="892">"Debenham Leisure Centre"</option>
          <option value="893">"Sizewell Sports & Social Club"</option>
          <option value="894">"Saxmundham Health"</option>
          <option value="895">"Sole Bay Health Centre"</option>
          <option value="896">"Jubilee Centre"</option>
          <option value="897">"Trinity Park Conference Centre"</option>
          <option value="898">"Hadleigh Health Centre"</option>
          <option value="899">"Leagrave Centre"</option>
          <option value="900">"Toddington Medical Centre"</option>
          <option value="901">"Leighton Buzzard Rugby Club"</option>
          <option value="902">"Newport Pagnell Medical Centre"</option>
          <option value="903">"Asplands Medical Centre"</option>
          <option value="904">"Guru Nanak Gurdwara"</option>
          <option value="905">"Whitehouse Medical Centre"</option>
          <option value="906">"The Market Surgery"</option>
          <option value="907">"Hoveton Village Hall"</option>
          <option value="908">"Poringland Community Centre"</option>
          <option value="909">"Sheringham Medical Practice"</option>
          <option value="910">"Rossi's leisure centre"</option>
          <option value="911">"Gurney Surgery"</option>
          <option value="912">"Drayton Surgery"</option>
          <option value="913">"Chadwell Medical Centre"</option>
          <option value="914">"Units 6, 7 and 7a"</option>
          <option value="915">"Belle Vue Baptist Church"</option>
          <option value="916">"Saxon Hall"</option>
          <option value="917">"Salvation Army"</option>
          <option value="918">"Benfleet Clinic"</option>
          <option value="919">"Thomas Walker Surgery"</option>
          <option value="920">"Thistlemoor Medical Centre"</option>
          <option value="921">"The Fleet Community Centre in conjuction with Greater Peterborough Network"</option>
          <option value="922">"The Old Exchange Surgery"</option>
          <option value="923">"Charles Hicks Centre"</option>
          <option value="924">"Snettisham Surgery"</option>
          <option value="925">"Manor Farm Medical Centre"</option>
          <option value="926">"BMC @ Werrington Surgery"</option>
          <option value="927">"The Jenner Health Centre"</option>
          <option value="928">"Kingswood Health Centre"</option>
          <option value="929">"EAST HULL FAMILY PRACTICE"</option>
          <option value="930">"Diadem Medical Practice"</option>
          <option value="931">"Ireland Wood Surgery"</option>
          <option value="932">"Bieghton Surgery"</option>
          <option value="933">"University Health Service Health Centre"</option>
          <option value="934">"Cleadon Park Primary Care Centre"</option>
          <option value="935">"Millfield Medical Group"</option>
          <option value="936">"The Garth"</option>
          <option value="937">"Thorntree Surgery"</option>
          <option value="938">"St Swithun's Community Centre"</option>
          <option value="939">"Wellington Street Car Park"</option>
          <option value="940">"Swanley Town Council, Alexandra Suite"</option>
          <option value="941">"Dover Health Centre"</option>
          <option value="942">"St Lawrence Surgery"</option>
          <option value="943">"Lancing Parish Hall"</option>
          <option value="944">"Westcourt Medical Centre"</option>
          <option value="945">"Brighton Racecourse"</option>
          <option value="946">"Dartford Football Club"</option>
          <option value="947">"G-Live"</option>
          <option value="948">"St Christopher's Church"</option>
          <option value="949">"Cranleigh Village Hall"</option>
          <option value="950">"Wycombe Town Hall"</option>
          <option value="951">"Mandeville Stadium"</option>
          <option value="952">"H&M Building"</option>
          <option value="953">"Fitznells Surgery"</option>
          <option value="954">"Rochester Healthy Living Centre & Lordswood Healthy Livng Centre"</option>
          <option value="955">"Heather House Day Centre"</option>
          <option value="956">"St Mary's Medical Centre"</option>
          <option value="957">"Grimsbury Community CeNotre,"</option>
          <option value="958">"Carterton Health Centre"</option>
          <option value="959">"The Selsey Centre"</option>
          <option value="960">"Tangmere Hall"</option>
          <option value="961">"Eldon Square Surgery"</option>
          <option value="962">"Birch Hill Medical Practice"</option>
          <option value="963">"Newbury Racecourse"</option>
          <option value="964">"Emmer Green Surgery"</option>
          <option value="965">"Meridian Hall"</option>
          <option value="966">"Tonbridge Baptist Church"</option>
          <option value="967">"Headcorn Surgery"</option>
          <option value="968">"Saxonbury House Medical Group"</option>
          <option value="969">"RAC Business Park"</option>
          <option value="970">"Archers Practice"</option>
          <option value="971">"Oaks Park Medical Centre"</option>
          <option value="972">"Paxton Green Group Practice"</option>
          <option value="973">"Sydenham Green Health Centre"</option>
          <option value="974">"Willesden Centre for Health & Care"</option>
          <option value="975">"Recreation Centre on Royal Free Hospital Site"</option>
          <option value="976">"Dr Azim and Partners"</option>
          <option value="977">"Mitcham Lane Baptist Church"</option>
          <option value="978">"Hetherington Group Practice"</option>
          <option value="979">"Parson's Green Health Centre"</option>
          <option value="980">"Community House"</option>
          <option value="981">"Downham Health and Leisure Centre"</option>
          <option value="982">"St Pauls Church"</option>
          <option value="983">"Fairfield Halls"</option>
          <option value="984">"Cable Street Surgery"</option>
          <option value="985">"Newby Place Health and Wellbeing Centre"</option>
          <option value="986">"Bocking Centre"</option>
          <option value="987">"Byron Hall"</option>
          <option value="988">"New Malden United Reformed Church"</option>
          <option value="989">"The Greenwood Centre"</option>
          <option value="990">"Thornbury Road Health Centre"</option>
          <option value="991">"Navnat Centre"</option>
          <option value="992">"White City Community Centre"</option>
          <option value="993">"Etchingham Village Hall"</option>
          <option value="994">"Lydd Airport"</option>
          <option value="995">"Buckingham Community Centre"</option>
          <option value="996">"Sussex Community NHS Foundation Trust – Pharmacy Dispensary"</option>
          <option value="997">"Folkestone Civic Centre"</option>
          <option value="998">"Riverbank Medical Centre"</option>
          <option value="999">"Clay Farm Medical Centre"</option>
          <option value="1000">"Over conference & Community Centre"</option>
          <option value="1001">"Milton Community Hall"</option>
          <option value="1002">"East Barnwell Health Centre"</option>
          <option value="1003">"Doddington Hospital"</option>
          <option value="1004">"Little Paxton"</option>
          <option value="1005">"Alconbury Practice"</option>
          <option value="1006">"Forest Recreation Ground"</option>
          <option value="1007">"St Johns House Medical Centre"</option>
          <option value="1008">"Ripon Air Cadets"</option>
          <option value="1009">"Plant Hill Clinic"</option>
          <option value="1010">"Kildonan House"</option>
          <option value="1011">"Littleborough Sports Centre"</option>
          <option value="1012">"Isles of Scilly Health Centre (deliver to mainland - Helston Medical Centre, Trelawney Road, Helston, TR13 8AU)"</option>
          <option value="1013">"Clays Practice"</option>
          <option value="1014">"Royston Health Centre"</option>

          </select>
        </f7-list-item>  

      </f7-list>
      <f7-button fill type ="submit"> Sign up </f7-button>
    </form>
  </f7-block>
  </f7-page>

</template>

<script> 
  import routes from '../js/routes.js';

  export default{


    data() {
      
      return {
        email: '', 
        name: '',
        password: '',
        centre: '',
        loggedOn: false,
      };
    },
    methods: {
      goBack() {
        this.$f7.views.main.router.navigate('/login/');
      },
      onSignupClicked(e){
        var res = {
          "name":this.name,
          "email": this.email,
          "password": this.password,
          "centre": this.centre
        }
        console.log(res);
        this.$f7.views.main.router.navigate('/adminHome/');
      },
      
    },
      
  };

</script>